name = "Microstates"
uuid = "ff92c308-9d97-4cdd-b14f-0ed5b2e54c3b"
authors = ["Gabriel Ferreira", "Sérgio Lopes", "Thiago Prado"]
version = "1.2.3-DEV"

[deps]
Distances = "b4f34e82-e78d-54a5-968a-f98e89d6e8f7"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"

[compat]
Distances = "0.7.0"
Statistics = "1.10.0"
StatsBase = "0.34.3"
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
